-- Ejecutar manualmente con un rol autorizado; crea recursos que pueden generar costos.
-- Configuración validada en Snowflake; no contiene credenciales.
-- Revisar costos y cuota antes de aprovisionar una cuenta nueva.
USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS TRAYECTORIAS_TEST_MONITOR
 WITH CREDIT_QUOTA=1 FREQUENCY=NEVER START_TIMESTAMP=IMMEDIATELY
 TRIGGERS ON 100 PERCENT DO SUSPEND_IMMEDIATE;
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS TRAYECTORIAS_WH
 WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE
 STATEMENT_TIMEOUT_IN_SECONDS=300;
USE ROLE ACCOUNTADMIN;
ALTER WAREHOUSE TRAYECTORIAS_WH SET RESOURCE_MONITOR=TRAYECTORIAS_TEST_MONITOR;
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS TRAYECTORIAS_AR;
CREATE SCHEMA IF NOT EXISTS TRAYECTORIAS_AR.RAW;
CREATE SCHEMA IF NOT EXISTS TRAYECTORIAS_AR.ANALYTICS;
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS TRAYECTORIAS_ROLE;
GRANT USAGE ON WAREHOUSE TRAYECTORIAS_WH TO ROLE TRAYECTORIAS_ROLE;
GRANT USAGE ON DATABASE TRAYECTORIAS_AR TO ROLE TRAYECTORIAS_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TRAYECTORIAS_AR TO ROLE TRAYECTORIAS_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA TRAYECTORIAS_AR.RAW TO ROLE TRAYECTORIAS_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA TRAYECTORIAS_AR.ANALYTICS TO ROLE TRAYECTORIAS_ROLE;
-- Un administrador debe asignar TRAYECTORIAS_ROLE al usuario de servicio
-- y registrar su clave pública. La clave privada permanece fuera del repositorio.
