const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ctx=DATA.context, digital=DATA.digital, sources=DATA.sources;
function bars(rows,unit='%'){return rows.map(r=>`<div class="barrow"><div>${escapeHtml(r.label)} <strong>${r.value==null?'Sin dato':fmt(r.value,1)+' '+escapeHtml(unit)}</strong></div><div class="track"><span style="width:${r.value==null?0:Math.max(0,Math.min(100,r.value))}%"></span></div></div>`).join('')}
function plot(rows,{interval=false,unit=''}={}){const w=680,h=310,left=55,right=18,top=25,bottom=70;const vals=rows.flatMap(r=>r.value==null?[]:interval?[r.ci95_low??r.value,r.ci95_high??r.value]:[r.value]);if(!vals.length)return '<p>Sin observaciones disponibles.</p>';let lo=interval?Math.min(...vals)-15:Math.min(0,...vals),hi=Math.max(...vals)*1.07;if(hi<=lo)hi=lo+1;const x=i=>left+i*(w-left-right)/Math.max(1,rows.length-1),y=v=>top+(hi-v)*(h-top-bottom)/(hi-lo);let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Serie de ${escapeHtml(unit)}">`;for(let i=0;i<5;i++){let v=lo+(hi-lo)*i/4;svg+=`<path d="M${left} ${y(v)} H${w-right}" stroke="#dfe6dc"/><text x="${left-8}" y="${y(v)+4}" text-anchor="end" font-size="11">${fmt(v,0)}</text>`}let seg=[];const flush=()=>{if(seg.length)svg+=`<polyline points="${seg.join(' ')}" fill="none" stroke="#096b5c" stroke-width="2.5"/>`;seg=[]};rows.forEach((r,i)=>{if(r.value==null){flush()}else{seg.push(`${x(i)},${y(r.value)}`);if(interval&&r.ci95_low!=null)svg+=`<path d="M${x(i)} ${y(r.ci95_low)} V${y(r.ci95_high)} M${x(i)-5} ${y(r.ci95_low)} h10 M${x(i)-5} ${y(r.ci95_high)} h10" stroke="#a66a40" stroke-width="2"/>`;svg+=`<circle cx="${x(i)}" cy="${y(r.value)}" r="4" fill="#096b5c"><title>${escapeHtml(r.label)}: ${fmt(r.value)} ${escapeHtml(unit)}</title></circle>`}if(rows.length<10||i%5===0||i===rows.length-1)svg+=`<text transform="translate(${x(i)},${h-bottom+20}) rotate(-28)" text-anchor="end" font-size="10">${escapeHtml(r.label)}</text>`});flush();return svg+'</svg>'}
const metrics=[...new Map(ctx.map(r=>[r.indicator,r])).values()];metrics.forEach(r=>$('metric').add(new Option(r.indicator_label,r.indicator)));$('metric').value='IT.NET.USER.ZS';
[...new Map(ctx.map(r=>[r.country_code,r.country_name])).entries()].sort().forEach(([c,n])=>$('country').add(new Option(n,c)));$('country').value='ARG';
for(let y=2025;y>=2000;y--)$('contextYear').add(new Option(y,y));$('contextYear').value='2024';
function updateNational(){const rows=ctx.filter(r=>r.indicator===$('metric').value&&r.country_code===$('country').value).sort((a,b)=>a.year-b.year),r=rows.find(r=>r.year===+$('contextYear').value),last=rows.filter(r=>r.value!=null).at(-1);$('metricTitle').textContent=r.indicator_label;$('wdiValue').textContent=r.value==null?'Sin dato para '+r.year:fmt(r.value)+' '+r.unit+' · '+r.year;$('wdiDefinition').textContent=r.method_note;$('wdiChart').innerHTML=plot(rows.map(r=>({...r,label:r.year})),{unit:r.unit});const peers=ctx.filter(s=>s.indicator===r.indicator&&s.year===r.year).sort((a,b)=>a.country_name.localeCompare(b.country_name));$('wdiCompare').innerHTML='<table><thead><tr><th>País</th><th>Valor · '+r.year+'</th></tr></thead><tbody>'+peers.map(p=>`<tr><td>${escapeHtml(p.country_name)}</td><td>${p.value==null?'Sin dato':fmt(p.value)+' '+escapeHtml(p.unit)}</td></tr>`).join('')+'</tbody></table>';$('freshness').textContent=last?`Último dato disponible para ${r.country_name}: ${last.year} (${fmt(last.value)} ${last.unit}). ${2025-last.year>=3?'Serie rezagada: no describe la situación actual.':''}`:'No hay observaciones para este país e indicador.'}
['metric','country','contextYear'].forEach(id=>$(id).addEventListener('change',updateNational));updateNational();
const kids=digital.filter(r=>r.source_id.startsWith('kids_'));
$('digitalCards').innerHTML=['redes_diario','videos_diario','chatgpt_alguna_vez','internet_escolar_diario'].map(id=>{const r=kids.find(r=>r.indicator===id&&r.subgroup==='Total');return `<article class="card"><div class="small">${escapeHtml(r.indicator_label)}</div><div class="number">${fmt(r.value,0)}%</div><div class="small muted">${escapeHtml(r.denominator)}</div></article>`}).join('');
$('aiBars').innerHTML=bars(kids.filter(r=>r.indicator==='chatgpt_alguna_vez').map(r=>({label:r.subgroup,value:r.value})));
$('kidsTable').innerHTML=kids.sort((a,b)=>a.indicator_label.localeCompare(b.indicator_label)).map(r=>`<tr><td>${escapeHtml(r.indicator_label)}<br><span class="muted">${escapeHtml(r.subgroup)}</span></td><td>${fmt(r.value,0)}</td><td style="text-align:left">${escapeHtml(r.denominator)}</td><td><a href="${escapeHtml(r.source_url)}#page=${r.source_locator.match(/página (\d+)/)[1]}">p. ${r.source_locator.match(/página (\d+)/)[1]}</a></td></tr>`).join('');
[...new Map(digital.filter(r=>r.source_id.startsWith('pisa')).map(r=>[r.country_code,r.country_name])).entries()].sort().forEach(([c,n])=>$('pisaCountry').add(new Option(n,c)));$('pisaCountry').value='ARG';
function updatePisa(){const rows=digital.filter(r=>r.country_code===$('pisaCountry').value),series=rows.filter(r=>r.indicator===$('purpose').value).sort((a,b)=>a.category_order-b.category_order);$('pisaChart').innerHTML=plot(series.map(r=>({...r,label:r.category})),{interval:true,unit:'puntos PISA'});const coef=rows.find(r=>r.indicator==='asociacion_ocio'&&r.category==='Ajuste socioeconómico');$('coefficient').textContent=fmt(coef.value)+' puntos / hora';$('coefficientNote').textContent=`Intervalo aproximado del 95%: ${fmt(coef.ci95_low)} a ${fmt(coef.ci95_high)}. `+(coef.ci95_low<=0&&coef.ci95_high>=0?'El intervalo incluye cero: esta estimación es compatible con una asociación nula.':coef.value<0?'La asociación estimada es negativa; no es una estimación causal.':'La asociación estimada es positiva; no es una estimación causal.');$('coefficientSource').textContent=coef.source_locator;$('distraction').innerHTML=['distraccion_propia','distraccion_ajena'].map(ind=>{const rs=rows.filter(r=>r.indicator===ind).sort((a,b)=>a.category_order-b.category_order);return `<div><h3>${escapeHtml(rs[0].indicator_label)}</h3>${bars(rs.map(r=>({label:r.category,value:r.value})))}</div>`}).join('')}
['pisaCountry','purpose'].forEach(id=>$(id).addEventListener('change',updatePisa));updatePisa();
$('pipelineCards').innerHTML=[[DATA.total,'Observaciones (incluye nulos)'],[DATA.context.length+DATA.digital.length,'Nuevos registros de contexto'],[DATA.families,'Familias de fuentes'],[sources.length,'Artefactos con hash']].map(([n,label])=>`<article class="card"><div class="number">${fmt(n,0)}</div><div class="small">${label}</div></article>`).join('');
$('sourceTable').innerHTML=sources.map(r=>`<tr><td><a href="${escapeHtml(r.url)}">${escapeHtml(r.source_id)}</a><br><span class="muted">${escapeHtml(r.producer)} · ${r.artifact_role}</span></td><td>${fmt(r.observations,0)}</td><td>${fmt(r.observed,0)}</td><td>${r.first_year??'—'} / ${r.last_year??'—'}</td><td><code title="${r.sha256}">${r.sha256.slice(0,10)}…</code><br>${escapeHtml(r.retrieved_at.slice(0,10))}</td></tr>`).join('');
document.querySelectorAll('.navbtn').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==button.dataset.panel);document.querySelectorAll('.navbtn').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
